import cors from 'cors';
import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaultCategories, defaultNasConfig, mockAlbums } from './mockData';
import type { Album, AppConfig, Category, MediaKind, NasConfig } from './types';

const app = express();
const port = Number(process.env.PORT || 8787);
const audioExtensions = new Set(['.mp3', '.m4a', '.m4b', '.aac', '.flac', '.wav', '.ogg', '.opus']);
const coverFileNames = ['cover.jpg', 'cover.jpeg', 'cover.png', 'folder.jpg', 'folder.jpeg', 'folder.png'];
const libraryFolderNames = new Set(['广播剧', '剧集', '有声书', '听书', '网课', '课程', 'course', 'courses', 'book', 'books', 'drama', 'dramas']);
const maxScanFiles = Number(process.env.MAX_SCAN_FILES || 2000);
const maxAutoGeneratedCoversPerScan = Number(process.env.MAX_AUTO_GENERATED_COVERS_PER_SCAN || 8);
const stateFile = path.resolve('data/state.json');
const coversDir = path.resolve('data/covers');

app.use(cors());
app.use(express.json());

type AppState = { nas: NasConfig; albums: Album[]; categories: Category[] };

function normalizeState(state: Partial<AppState>): AppState {
  const defaultAlbumMap = new Map(mockAlbums.map((album) => [album.id, album]));
  const existingAlbums = state.albums?.length ? state.albums : mockAlbums;
  const albums = existingAlbums.map((album) => {
    const defaultAlbum = defaultAlbumMap.get(album.id);
    if (!defaultAlbum) return album;
    const hasCustomCover = album.cover?.startsWith('data:image/');
    return {
      ...defaultAlbum,
      ...album,
      cover: hasCustomCover ? album.cover : defaultAlbum.cover,
      tags: [...new Set([...(defaultAlbum.tags || []), ...(album.tags || [])])]
    };
  });

  return {
    nas: state.nas || defaultNasConfig,
    albums,
    categories: state.categories?.length ? state.categories : defaultCategories
  };
}

function readState(): AppState {
  if (!fs.existsSync(stateFile)) {
    return { nas: defaultNasConfig, albums: mockAlbums, categories: defaultCategories };
  }

  const raw = fs.readFileSync(stateFile, 'utf-8');
  return normalizeState(JSON.parse(raw));
}

function writeState(state: AppState) {
  fs.mkdirSync(path.dirname(stateFile), { recursive: true });
  fs.writeFileSync(stateFile, JSON.stringify(state, null, 2));
}

function getConfig(): AppConfig {
  return {
    name: 'private-audio-room',
    publicUrl: process.env.PUBLIC_APP_URL || '',
    mediaRoot: process.env.AUDIO_ROOT || '',
    maxScanFiles,
    supportedAudioExtensions: [...audioExtensions],
    supportedCoverNames: coverFileNames
  };
}

function shouldAutoGenerateCovers() {
  return process.env.AUTO_GENERATE_COVERS === 'true' && Boolean(process.env.OPENAI_API_KEY);
}

function inferKindFromPath(filePath: string): MediaKind {
  const normalized = filePath.toLowerCase();
  if (normalized.includes('课程') || normalized.includes('course') || normalized.includes('课')) return 'course';
  if (normalized.includes('book') || normalized.includes('有声书') || normalized.includes('听书')) return 'book';
  return 'drama';
}

function isPathInsideRoot(filePath: string, root: string) {
  const relative = path.relative(path.resolve(root), path.resolve(filePath));
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
}

function safeStat(filePath: string) {
  try {
    return fs.statSync(filePath);
  } catch {
    return null;
  }
}

function findFolderCover(folderPath: string) {
  for (const fileName of coverFileNames) {
    const coverPath = path.join(folderPath, fileName);
    const stat = safeStat(coverPath);
    if (!stat?.isFile()) continue;

    const ext = path.extname(fileName).toLowerCase();
    const mime = ext === '.png' ? 'image/png' : 'image/jpeg';
    const data = fs.readFileSync(coverPath);
    return `data:${mime};base64,${data.toString('base64')}`;
  }

  return '';
}

function audioContentType(filePath: string) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === '.mp3') return 'audio/mpeg';
  if (ext === '.m4a' || ext === '.m4b' || ext === '.aac') return 'audio/mp4';
  if (ext === '.flac') return 'audio/flac';
  if (ext === '.wav') return 'audio/wav';
  if (ext === '.ogg' || ext === '.opus') return 'audio/ogg';
  return 'application/octet-stream';
}

function fallbackCover(kind: MediaKind) {
  if (kind === 'drama') return 'linear-gradient(145deg, #3d1d51 0%, #ff5aa5 55%, #ffd1e8 100%)';
  if (kind === 'book') return 'linear-gradient(145deg, #332a7a 0%, #8e4cff 52%, #d8ccff 100%)';
  return 'linear-gradient(145deg, #06474a 0%, #34a0a4 52%, #c7f7ef 100%)';
}

function isPlaceholderCover(cover: string) {
  return cover.startsWith('linear-gradient(');
}

function safeFileName(value: string) {
  return value.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 80);
}

function coverPromptForAlbum(album: Album) {
  const kindLabel = album.kind === 'drama' ? 'Chinese audio drama' : album.kind === 'book' ? 'Chinese audiobook' : 'Chinese online course';
  return [
    `Create square cover art for a private ${kindLabel}.`,
    `Title: ${album.title}`,
    `Subtitle/context: ${album.subtitle}`,
    `Tags: ${album.tags.join(', ')}`,
    `Description: ${album.description}`,
    'Style: refined pencil sketch with selective muted color accents, clean white/cream background, elegant Chinese audio app aesthetic, subtle ink lines, soft cinematic lighting.',
    'Composition: premium square album cover, readable title area, strong focal image, restrained and tasteful, mobile-app ready.',
    'Avoid: fan community features, celebrity/idol elements, internet platform UI, messy text, watermark, logos, neon gradient placeholder, childish cartoon.'
  ].join('\n');
}

async function generateAlbumCover(album: Album) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is not configured');

  const model = process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1';
  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model,
      prompt: coverPromptForAlbum(album),
      size: '1024x1024'
    })
  });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(`OpenAI image generation failed: ${message.slice(0, 240)}`);
  }

  const data = (await response.json()) as { data?: Array<{ b64_json?: string; url?: string }> };
  let imageBytes: Buffer | null = null;
  const first = data.data?.[0];

  if (first?.b64_json) {
    imageBytes = Buffer.from(first.b64_json, 'base64');
  } else if (first?.url) {
    const imageResponse = await fetch(first.url);
    if (!imageResponse.ok) throw new Error('Generated image URL could not be downloaded');
    imageBytes = Buffer.from(await imageResponse.arrayBuffer());
  }

  if (!imageBytes) throw new Error('OpenAI did not return image data');

  fs.mkdirSync(coversDir, { recursive: true });
  const fileName = `${safeFileName(album.id)}.png`;
  fs.writeFileSync(path.join(coversDir, fileName), imageBytes);
  return `/covers/${fileName}`;
}

async function generateMissingCovers(albums: Album[], limit = maxAutoGeneratedCoversPerScan) {
  if (!shouldAutoGenerateCovers()) return { albums, generated: 0, failed: 0 };

  let generated = 0;
  let failed = 0;
  const nextAlbums: Album[] = [];

  for (const album of albums) {
    if (generated >= limit || !isPlaceholderCover(album.cover)) {
      nextAlbums.push(album);
      continue;
    }

    try {
      const cover = await generateAlbumCover(album);
      nextAlbums.push({ ...album, cover });
      generated += 1;
    } catch (error) {
      console.warn(`Cover generation failed for ${album.title}:`, error);
      nextAlbums.push(album);
      failed += 1;
    }
  }

  return { albums: nextAlbums, generated, failed };
}

function naturalSort(values: string[]) {
  return [...values].sort((a, b) => a.localeCompare(b, 'zh-Hans-CN', { numeric: true, sensitivity: 'base' }));
}

function normalizeDisplayName(value: string) {
  return value
    .replace(/\.[a-z0-9]{2,5}$/i, '')
    .replace(/[._-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function stripNoise(value: string) {
  return normalizeDisplayName(value)
    .replace(/【[^】]*】/g, '')
    .replace(/\[[^\]]*]/g, '')
    .replace(/（[^）]*）/g, '')
    .replace(/\([^)]*\)/g, '')
    .replace(/\b(mp3|m4a|m4b|flac|aac|wav|opus|ogg)\b/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function albumInfoForFile(root: string, file: string) {
  const relativeFile = path.relative(root, file);
  const parts = relativeFile.split(path.sep).filter(Boolean);
  const directoryParts = parts.slice(0, -1);

  if (!directoryParts.length) {
    return {
      key: path.basename(root),
      folderPath: root,
      title: normalizeDisplayName(path.basename(root))
    };
  }

  const first = directoryParts[0].toLowerCase();
  if (libraryFolderNames.has(directoryParts[0]) || libraryFolderNames.has(first)) {
    const albumPart = directoryParts[1] || directoryParts[0];
    const keyParts = directoryParts[1] ? directoryParts.slice(0, 2) : directoryParts.slice(0, 1);
    return {
      key: keyParts.join(path.sep),
      folderPath: path.join(root, ...keyParts),
      title: normalizeDisplayName(albumPart)
    };
  }

  return {
    key: directoryParts[0],
    folderPath: path.join(root, directoryParts[0]),
    title: normalizeDisplayName(directoryParts[0])
  };
}

function cleanEpisodeTitle(file: string, albumTitle: string, index: number) {
  const fallback = `${String(index + 1).padStart(2, '0')}`;
  const albumTokens = new Set(
    stripNoise(albumTitle)
      .split(/\s+/)
      .filter((token) => token.length > 1)
  );
  const raw = stripNoise(path.basename(file, path.extname(file)));
  const withoutAlbum = raw
    .split(/\s+/)
    .filter((token) => !albumTokens.has(token))
    .join(' ')
    .replace(/^(广播剧|有声书|网课|课程)\s*/i, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (!withoutAlbum) return fallback;
  if (withoutAlbum.length > 42 && /(\d{1,4}|[一二三四五六七八九十百零〇两]+)\s*(集|期|话|章)?/.test(withoutAlbum)) {
    return fallback;
  }

  return withoutAlbum;
}

function listAudioFiles(root: string, limit = maxScanFiles) {
  const files: string[] = [];

  function walk(dir: string) {
    if (files.length >= limit) return;
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (files.length >= limit) return;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!entry.name.startsWith('.')) walk(fullPath);
      } else if (audioExtensions.has(path.extname(entry.name).toLowerCase())) {
        files.push(fullPath);
      }
    }
  }

  walk(root);
  return files;
}

function albumsFromFiles(root: string, files: string[]): Album[] {
  const groups = new Map<string, { folderPath: string; title: string; files: string[] }>();
  for (const file of files) {
    const albumInfo = albumInfoForFile(root, file);
    const group = groups.get(albumInfo.key) || { folderPath: albumInfo.folderPath, title: albumInfo.title, files: [] };
    group.files.push(file);
    groups.set(albumInfo.key, group);
  }

  return [...groups.entries()].map(([group, albumGroup], index) => {
    const sortedFiles = naturalSort(albumGroup.files);
    const kind = inferKindFromPath(group);
    const title = albumGroup.title || `本地专辑 ${index + 1}`;
    const folderCover = findFolderCover(albumGroup.folderPath);
    return {
      id: `local-${index}-${Buffer.from(group).toString('base64url').slice(0, 10)}`,
      kind,
      title,
      subtitle: `${kind === 'drama' ? '广播剧' : kind === 'book' ? '有声书' : '网课'} · ${sortedFiles.length} 集`,
      cover: folderCover || fallbackCover(kind),
      creator: 'NAS 本地文件',
      status: 'new',
      progress: 0,
      totalEpisodes: sortedFiles.length,
      updatedAt: '刚刚扫描',
      tags: ['NAS', kind === 'drama' ? '广播剧' : kind === 'book' ? '有声书' : '网课'],
      description: `来自 NAS 目录：${group}`,
      episodes: sortedFiles.map((file, fileIndex) => ({
        id: `local-${index}-${fileIndex}`,
        title: cleanEpisodeTitle(file, title, fileIndex),
        duration: '--:--',
        progress: 0,
        filePath: file
      }))
    };
  });
}

app.get('/api/health', (_req, res) => {
  res.json({ ok: true, name: 'private-audio-room' });
});

app.get('/api/config', (_req, res) => {
  res.json({ config: getConfig() });
});

app.get('/api/albums', (req, res) => {
  const kind = req.query.kind as MediaKind | undefined;
  const query = String(req.query.q || '').trim().toLowerCase();
  const state = readState();
  let albums = state.albums;

  if (kind) albums = albums.filter((album) => album.kind === kind);
  if (query) {
    albums = albums.filter((album) => {
      return [album.title, album.subtitle, album.creator, album.description, ...album.tags].some((value) =>
        value.toLowerCase().includes(query)
      );
    });
  }

  const category = String(req.query.category || '').trim();
  if (category) albums = albums.filter((album) => album.tags.includes(category));

  res.json({ albums });
});

app.get('/api/albums/:id', (req, res) => {
  const album = readState().albums.find((item) => item.id === req.params.id);
  if (!album) return res.status(404).json({ error: 'Album not found' });
  res.json({ album });
});

app.patch('/api/albums/:id/cover', (req, res) => {
  const cover = String(req.body.cover || '').trim();
  if (!cover) return res.status(400).json({ error: 'Cover is required' });
  if (!cover.startsWith('data:image/') && !cover.startsWith('linear-gradient(') && !cover.startsWith('/covers/')) {
    return res.status(400).json({ error: 'Cover must be an image data URL or supported gradient' });
  }

  const state = readState();
  const albumIndex = state.albums.findIndex((item) => item.id === req.params.id);
  if (albumIndex < 0) return res.status(404).json({ error: 'Album not found' });

  state.albums[albumIndex] = { ...state.albums[albumIndex], cover };
  writeState(state);
  res.json({ album: state.albums[albumIndex] });
});

app.post('/api/albums/:id/cover/generate', async (req, res) => {
  if (!process.env.OPENAI_API_KEY) {
    return res.status(400).json({ error: 'OPENAI_API_KEY is not configured' });
  }

  const state = readState();
  const albumIndex = state.albums.findIndex((item) => item.id === req.params.id);
  if (albumIndex < 0) return res.status(404).json({ error: 'Album not found' });

  try {
    const cover = await generateAlbumCover(state.albums[albumIndex]);
    state.albums[albumIndex] = { ...state.albums[albumIndex], cover };
    writeState(state);
    res.json({ album: state.albums[albumIndex] });
  } catch (error) {
    res.status(502).json({ error: error instanceof Error ? error.message : 'Cover generation failed' });
  }
});

app.get('/api/categories', (_req, res) => {
  res.json({ categories: readState().categories });
});

app.post('/api/categories', (req, res) => {
  const name = String(req.body.name || '').trim();
  if (!name) return res.status(400).json({ error: 'Category name is required' });

  const state = readState();
  const existing = state.categories.find((category) => category.name === name);
  if (existing) return res.json({ category: existing, categories: state.categories });

  const category: Category = {
    id: Buffer.from(name).toString('base64url').slice(0, 16),
    name
  };
  state.categories = [...state.categories, category];
  writeState(state);
  res.json({ category, categories: state.categories });
});

app.get('/api/nas', (_req, res) => {
  res.json({ nas: readState().nas });
});

app.post('/api/nas', (req, res) => {
  const current = readState();
  const root = String(req.body.root || '').trim();
  const nas: NasConfig = {
    type: req.body.type || 'local',
    label: req.body.label || '本地挂载 NAS',
    root,
    connected: root ? fs.existsSync(root) : false,
    lastScanAt: current.nas.lastScanAt
  };
  const next = { ...current, nas };
  writeState(next);
  res.json({ nas });
});

app.post('/api/scan', async (_req, res) => {
  const state = readState();
  const root = state.nas.root || process.env.AUDIO_ROOT || '';

  if (!root || !fs.existsSync(root)) {
    return res.status(400).json({ error: 'NAS root is not configured or not reachable' });
  }

  const files = listAudioFiles(root);
  const scannedAlbums = albumsFromFiles(root, files);
  const coverResult = await generateMissingCovers(scannedAlbums);
  const next = {
    nas: { ...state.nas, connected: true, lastScanAt: new Date().toISOString() },
    albums: coverResult.albums.length ? coverResult.albums : state.albums,
    categories: state.categories
  };
  writeState(next);
  res.json({
    albums: next.albums,
    count: files.length,
    nas: next.nas,
    covers: { generated: coverResult.generated, failed: coverResult.failed }
  });
});

app.get('/media/:albumId/:episodeId', (req, res) => {
  const state = readState();
  const album = state.albums.find((item) => item.id === req.params.albumId);
  const episode = album?.episodes.find((item) => item.id === req.params.episodeId);
  if (!episode?.filePath) return res.status(404).json({ error: 'Media file not found' });

  const resolved = path.resolve(episode.filePath);
  const root = path.resolve(state.nas.root || process.env.AUDIO_ROOT || path.dirname(resolved));
  if (!isPathInsideRoot(resolved, root) || !fs.existsSync(resolved)) {
    return res.status(403).json({ error: 'Media path is not allowed' });
  }

  const stat = fs.statSync(resolved);
  const fileSize = stat.size;
  const range = req.headers.range;
  const contentType = audioContentType(resolved);

  if (!range) {
    res.writeHead(200, {
      'Accept-Ranges': 'bytes',
      'Content-Length': fileSize,
      'Content-Type': contentType
    });
    fs.createReadStream(resolved).pipe(res);
    return;
  }

  const match = range.match(/bytes=(\d*)-(\d*)/);
  if (!match) return res.status(416).json({ error: 'Invalid range' });

  const start = match[1] ? Number(match[1]) : match[2] ? Math.max(fileSize - Number(match[2]), 0) : 0;
  const end = match[1] ? (match[2] ? Number(match[2]) : fileSize - 1) : fileSize - 1;
  if (start >= fileSize || end >= fileSize || start > end) {
    res.status(416).set('Content-Range', `bytes */${fileSize}`).end();
    return;
  }

  res.writeHead(206, {
    'Accept-Ranges': 'bytes',
    'Content-Range': `bytes ${start}-${end}/${fileSize}`,
    'Content-Length': end - start + 1,
    'Content-Type': contentType
  });
  fs.createReadStream(resolved, { start, end }).pipe(res);
});

const dirname = path.dirname(fileURLToPath(import.meta.url));
const distPath = path.resolve(dirname, '../dist');
app.use('/covers', express.static(coversDir));
if (fs.existsSync(distPath)) {
  app.use(express.static(distPath));
  app.get(/.*/, (_req, res) => res.sendFile(path.join(distPath, 'index.html')));
}

app.listen(port, () => {
  console.log(`Private Audio Room API listening on http://localhost:${port}`);
});
