import cors from 'cors';
import express from 'express';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaultCategories, defaultNasConfig, mockAlbums } from './mockData';
import type { Album, AlbumRecommendation, AppConfig, Category, FavoriteFolder, MediaKind, NasConfig, UserProfile } from './types';

const app = express();
const port = Number(process.env.PORT || 8787);
const audioExtensions = new Set(['.mp3', '.m4a', '.m4b', '.aac', '.flac', '.wav', '.ogg', '.opus']);
const audioSuffixes = [...audioExtensions].map((extension) => extension.slice(1));
const coverFileNames = ['cover.jpg', 'cover.jpeg', 'cover.png', 'folder.jpg', 'folder.jpeg', 'folder.png'];
const libraryFolderNames = new Set(['广播剧', '剧集', '有声书', '听书', '网课', '课程', 'course', 'courses', 'book', 'books', 'drama', 'dramas']);
const maxScanFiles = Number(process.env.MAX_SCAN_FILES || 2000);
const maxAutoGeneratedCoversPerScan = Number(process.env.MAX_AUTO_GENERATED_COVERS_PER_SCAN || 8);
const stateFile = path.resolve('data/state.json');
const coversDir = path.resolve('data/covers');

app.use(cors());
app.use(express.json());

type AppState = { nas: NasConfig; albums: Album[]; categories: Category[]; favoriteFolders: FavoriteFolder[]; profile: UserProfile };
type AiMetadata = {
  author: string;
  cast: string[];
  summary: string;
  genres: string[];
  relationship: string;
  audience: string;
  finishStatus: string;
  confidence: number;
  needsReview: boolean;
};

function normalizeState(state: Partial<AppState>): AppState {
  const defaultAlbumMap = new Map(mockAlbums.map((album) => [album.id, album]));
  const existingAlbums = state.albums?.length ? state.albums : mockAlbums;
  const albums = existingAlbums.map((album) => {
    const defaultAlbum = defaultAlbumMap.get(album.id);
    if (!defaultAlbum) return album;
    const hasCustomCover =
      album.cover?.startsWith('data:image/') || album.cover?.startsWith('/covers/') || album.cover?.startsWith('/assets/');
    return {
      ...defaultAlbum,
      ...album,
      cover: hasCustomCover ? album.cover : defaultAlbum.cover,
      tags: uniqueStrings([...(defaultAlbum.tags || []), ...(album.tags || [])]),
      cast: uniqueStrings(album.cast || defaultAlbum.cast || []),
      genres: uniqueStrings(album.genres || defaultAlbum.genres || [])
    };
  });

  return {
    nas: state.nas || defaultNasConfig,
    albums,
    categories: state.categories?.length ? state.categories : defaultCategories,
    favoriteFolders: normalizeFavoriteFolders(state.favoriteFolders),
    profile: state.profile || { avatar: '' }
  };
}

function readState(): AppState {
  if (!fs.existsSync(stateFile)) {
    return {
      nas: defaultNasConfig,
      albums: mockAlbums,
      categories: defaultCategories,
      favoriteFolders: normalizeFavoriteFolders([]),
      profile: { avatar: '' }
    };
  }

  const raw = fs.readFileSync(stateFile, 'utf-8');
  return normalizeState(JSON.parse(raw));
}

function writeState(state: AppState) {
  fs.mkdirSync(path.dirname(stateFile), { recursive: true });
  fs.writeFileSync(stateFile, JSON.stringify(state, null, 2));
}

function nowIso() {
  return new Date().toISOString();
}

function normalizeFavoriteFolders(folders?: FavoriteFolder[]) {
  const now = nowIso();
  const normalized = (folders || []).map((folder) => ({
    id: folder.id || `fav-${stableId(folder.name || now)}`,
    name: stringField(folder.name, 40) || '默认收藏夹',
    albumIds: uniqueStrings(folder.albumIds || []),
    createdAt: folder.createdAt || now,
    updatedAt: folder.updatedAt || now
  }));

  if (!normalized.some((folder) => folder.id === 'default')) {
    return [
      {
        id: 'default',
        name: '默认收藏夹',
        albumIds: [],
        createdAt: now,
        updatedAt: now
      },
      ...normalized
    ];
  }

  return normalized;
}

function getConfig(): AppConfig {
  return {
    name: 'private-audio-room',
    publicUrl: process.env.PUBLIC_APP_URL || '',
    mediaRoot: process.env.AUDIO_ROOT || '',
    maxScanFiles,
    supportedAudioExtensions: [...audioExtensions],
    supportedCoverNames: coverFileNames
  };
}

function shouldAutoGenerateCovers() {
  return process.env.AUTO_GENERATE_COVERS === 'true' && Boolean(process.env.OPENAI_API_KEY);
}

function inferKindFromPath(filePath: string): MediaKind {
  const normalized = filePath.toLowerCase();
  if (normalized.includes('课程') || normalized.includes('course') || normalized.includes('课')) return 'course';
  if (normalized.includes('book') || normalized.includes('有声书') || normalized.includes('听书')) return 'book';
  return 'drama';
}

function uniqueStrings(values: unknown[]) {
  return [...new Set(values.map((value) => String(value || '').trim()).filter(Boolean))];
}

function stringField(value: unknown, maxLength = 600) {
  return String(value || '').trim().slice(0, maxLength);
}

function arrayField(value: unknown, maxItems = 12) {
  if (Array.isArray(value)) return uniqueStrings(value).slice(0, maxItems);
  return uniqueStrings(String(value || '').split(/[，,、\n]/)).slice(0, maxItems);
}

function metadataPatchFromBody(body: Record<string, unknown>) {
  return {
    author: stringField(body.author, 80),
    cast: arrayField(body.cast, 20),
    summary: stringField(body.summary, 1200),
    genres: arrayField(body.genres, 16),
    relationship: stringField(body.relationship, 30),
    audience: stringField(body.audience, 30),
    finishStatus: stringField(body.finishStatus, 30),
    tags: arrayField(body.tags, 24),
    description: stringField(body.description, 1200)
  };
}

function aiMetadataFromBody(body: Record<string, unknown>): AiMetadata {
  return {
    author: stringField(body.author, 80),
    cast: arrayField(body.cast, 20),
    summary: stringField(body.summary || body.shortSummary, 1200),
    genres: arrayField(body.genres, 16),
    relationship: stringField(body.relationship, 30),
    audience: stringField(body.audience, 30),
    finishStatus: stringField(body.finishStatus, 30),
    confidence: Math.max(0, Math.min(1, Number(body.confidence || 0))),
    needsReview: body.needsReview !== false
  };
}

function extractJsonObject(text: string) {
  const cleaned = text
    .replace(/^```(?:json)?/i, '')
    .replace(/```$/i, '')
    .trim();
  try {
    return JSON.parse(cleaned);
  } catch {
    const match = cleaned.match(/\{[\s\S]*\}/);
    if (!match) throw new Error('DeepSeek did not return JSON');
    return JSON.parse(match[0]);
  }
}

async function analyzeAlbumMetadataWithDeepSeek(album: Album) {
  const apiKey = process.env.DEEPSEEK_API_KEY;
  if (!apiKey) throw new Error('DEEPSEEK_API_KEY is not configured');

  const model = process.env.DEEPSEEK_MODEL || 'deepseek-chat';
  const baseUrl = process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com/chat/completions';
  const episodeTitles = album.episodes.slice(0, 40).map((episode, index) => `${index + 1}. ${episode.title}`).join('\n');
  const prompt = [
    '你是一个私人 NAS 广播剧资料整理助手。请根据本地文件信息推断广播剧元数据。',
    '不要联网，不要编造确定信息；不确定时留空或降低 confidence，并设置 needsReview=true。',
    '只返回 JSON，不要 Markdown，不要解释。',
    '',
    '允许的 relationship：言情、耽美、百合、无 CP、群像、空字符串。',
    '允许的 audience：男女、男男、女女、群像、空字符串。',
    '允许的 finishStatus：已完结、连载中、未知。',
    'genres 用短标签，例如：现代、古风、悬疑、恐怖、刑侦、甜宠、虐恋、权谋、无限流、校园、娱乐圈、修仙、治愈、强强。',
    '',
    `标题：${album.title}`,
    `副标题：${album.subtitle}`,
    `当前作者/创建者：${album.author || album.creator || ''}`,
    `当前标签：${[...(album.tags || []), ...(album.genres || [])].join('、')}`,
    `当前简介：${album.summary || album.description || ''}`,
    `总集数：${album.totalEpisodes}`,
    `分集标题：\n${episodeTitles}`,
    '',
    '返回格式：',
    '{"author":"","cast":[],"summary":"","genres":[],"relationship":"","audience":"","finishStatus":"未知","confidence":0.5,"needsReview":true}'
  ].join('\n');

  const response = await fetch(baseUrl, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: '你负责把广播剧资料整理成严格 JSON。' },
        { role: 'user', content: prompt }
      ]
    })
  });

  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = data?.error?.message || data?.message || 'DeepSeek metadata analysis failed';
    throw new Error(message);
  }

  const content = data?.choices?.[0]?.message?.content;
  if (!content) throw new Error('DeepSeek returned empty metadata');
  return aiMetadataFromBody(extractJsonObject(content));
}

function applyAiMetadataToAlbum(album: Album, metadata: AiMetadata): Album {
  const nextTags = uniqueStrings([...(album.tags || []), ...(metadata.genres || [])]);
  return {
    ...album,
    author: metadata.author || album.author,
    cast: metadata.cast.length ? metadata.cast : album.cast,
    summary: metadata.summary || album.summary,
    description: metadata.summary || album.description,
    genres: metadata.genres.length ? metadata.genres : album.genres,
    relationship: metadata.relationship || album.relationship,
    audience: metadata.audience || album.audience,
    finishStatus: metadata.finishStatus || album.finishStatus,
    tags: nextTags.length ? nextTags : album.tags,
    updatedAt: '刚刚整理',
    aiMetaStatus: 'saved',
    aiMetaUpdatedAt: new Date().toISOString()
  };
}

const genericRecommendationTerms = new Set(['nas', '本地', '广播剧', '有声书', '网课', '课程', '听书', '未知']);

function comparableTerms(values: Array<string | undefined>) {
  return uniqueStrings(values).filter((value) => !genericRecommendationTerms.has(value.toLowerCase()));
}

function sharedTerms(source: Array<string | undefined>, target: Array<string | undefined>) {
  const targetSet = new Set(comparableTerms(target));
  return comparableTerms(source).filter((value) => targetSet.has(value));
}

function addRecommendationReason(reasons: string[], reason: string) {
  if (reason && !reasons.includes(reason)) reasons.push(reason);
}

function scoreAlbumRecommendation(source: Album, candidate: Album): AlbumRecommendation | null {
  if (source.id === candidate.id) return null;

  let score = 0;
  const reasons: string[] = [];

  if (source.author && candidate.author && source.author === candidate.author) {
    score += 5;
    addRecommendationReason(reasons, `同作者：${source.author}`);
  }

  const sharedCast = sharedTerms(source.cast || [], candidate.cast || []);
  if (sharedCast.length) {
    score += Math.min(sharedCast.length, 3) * 3;
    addRecommendationReason(reasons, `同配音：${sharedCast.slice(0, 2).join('、')}`);
  }

  if (source.relationship && candidate.relationship && source.relationship === candidate.relationship) {
    score += 3;
    addRecommendationReason(reasons, source.relationship);
  }

  if (source.audience && candidate.audience && source.audience === candidate.audience) {
    score += 2;
    addRecommendationReason(reasons, source.audience);
  }

  const sharedGenres = sharedTerms([...(source.genres || []), ...(source.tags || [])], [...(candidate.genres || []), ...(candidate.tags || [])]);
  if (sharedGenres.length) {
    score += Math.min(sharedGenres.length, 4) * 2;
    addRecommendationReason(reasons, sharedGenres.slice(0, 3).join('、'));
  }

  if (source.finishStatus && candidate.finishStatus && source.finishStatus === candidate.finishStatus && source.finishStatus !== '未知') {
    score += 1;
    addRecommendationReason(reasons, source.finishStatus);
  }

  if (score <= 0 && source.kind === candidate.kind) {
    score = 1;
    addRecommendationReason(reasons, `同为${kindLabel(source.kind)}`);
  }

  if (score <= 0) return null;
  return { album: candidate, score, reasons };
}

function kindLabel(kind: MediaKind) {
  if (kind === 'book') return '有声书';
  if (kind === 'course') return '网课';
  return '广播剧';
}

function getAlbumRecommendations(album: Album, albums: Album[], limit = 6) {
  return albums
    .map((candidate) => scoreAlbumRecommendation(album, candidate))
    .filter((recommendation): recommendation is AlbumRecommendation => Boolean(recommendation))
    .sort((a, b) => b.score - a.score || b.album.progress - a.album.progress || a.album.title.localeCompare(b.album.title, 'zh-Hans-CN'))
    .slice(0, limit);
}

function mergeManualMetadata(scanned: Album[], existing: Album[]) {
  const existingById = new Map(existing.map((album) => [album.id, album]));
  const existingByTitle = new Map(existing.map((album) => [album.title, album]));
  return scanned.map((album) => {
    const previous = existingById.get(album.id) || existingByTitle.get(album.title);
    if (!previous) return album;
    const hasCustomCover =
      previous.cover?.startsWith('data:image/') || previous.cover?.startsWith('/covers/') || previous.cover?.startsWith('/assets/');
    return {
      ...album,
      cover: hasCustomCover ? previous.cover : album.cover,
      status: previous.status || album.status,
      progress: previous.progress || album.progress,
      tags: uniqueStrings([...(album.tags || []), ...(previous.tags || []), ...(previous.genres || [])]),
      description: previous.description && previous.description !== `来自 NAS 目录：${album.title}` ? previous.description : album.description,
      author: previous.author || album.author,
      cast: uniqueStrings(previous.cast || album.cast || []),
      summary: previous.summary || album.summary,
      genres: uniqueStrings(previous.genres || album.genres || []),
      relationship: previous.relationship || album.relationship,
      audience: previous.audience || album.audience,
      finishStatus: previous.finishStatus || album.finishStatus,
      aiMetaStatus: previous.aiMetaStatus || album.aiMetaStatus,
      aiMetaUpdatedAt: previous.aiMetaUpdatedAt || album.aiMetaUpdatedAt
    };
  });
}

function isPathInsideRoot(filePath: string, root: string) {
  const relative = path.relative(path.resolve(root), path.resolve(filePath));
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
}

function safeStat(filePath: string) {
  try {
    return fs.statSync(filePath);
  } catch {
    return null;
  }
}

function findFolderCover(folderPath: string) {
  for (const fileName of coverFileNames) {
    const coverPath = path.join(folderPath, fileName);
    const stat = safeStat(coverPath);
    if (!stat?.isFile()) continue;

    const ext = path.extname(fileName).toLowerCase();
    const mime = ext === '.png' ? 'image/png' : 'image/jpeg';
    const data = fs.readFileSync(coverPath);
    return `data:${mime};base64,${data.toString('base64')}`;
  }

  return '';
}

function audioContentType(filePath: string) {
  const lower = filePath.toLowerCase();
  const ext = path.extname(lower);
  if (ext === '.mp3') return 'audio/mpeg';
  if (ext === '.m4a' || ext === '.m4b' || ext === '.aac') return 'audio/mp4';
  if (ext === '.flac') return 'audio/flac';
  if (ext === '.wav') return 'audio/wav';
  if (ext === '.ogg' || ext === '.opus') return 'audio/ogg';
  if (lower.endsWith('mp3')) return 'audio/mpeg';
  if (lower.endsWith('m4a') || lower.endsWith('m4b') || lower.endsWith('aac')) return 'audio/mp4';
  if (lower.endsWith('flac')) return 'audio/flac';
  if (lower.endsWith('wav')) return 'audio/wav';
  if (lower.endsWith('ogg') || lower.endsWith('opus')) return 'audio/ogg';
  return 'application/octet-stream';
}

function fallbackCover(kind: MediaKind) {
  if (kind === 'drama') return 'linear-gradient(145deg, #3d1d51 0%, #ff5aa5 55%, #ffd1e8 100%)';
  if (kind === 'book') return 'linear-gradient(145deg, #332a7a 0%, #8e4cff 52%, #d8ccff 100%)';
  return 'linear-gradient(145deg, #06474a 0%, #34a0a4 52%, #c7f7ef 100%)';
}

function isPlaceholderCover(cover: string) {
  return cover.startsWith('linear-gradient(');
}

function safeFileName(value: string) {
  return value.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 80);
}

function stableId(value: string, length = 18) {
  return crypto.createHash('sha1').update(value).digest('base64url').slice(0, length);
}

function coverPromptForAlbum(album: Album) {
  const kindLabel = album.kind === 'drama' ? 'Chinese audio drama' : album.kind === 'book' ? 'Chinese audiobook' : 'Chinese online course';
  return [
    `Create square cover art for a private ${kindLabel}.`,
    `Title: ${album.title}`,
    `Subtitle/context: ${album.subtitle}`,
    `Tags: ${album.tags.join(', ')}`,
    `Description: ${album.description}`,
    'Style: refined pencil sketch with selective muted color accents, clean white/cream background, elegant Chinese audio app aesthetic, subtle ink lines, soft cinematic lighting.',
    'Composition: premium square album cover, readable title area, strong focal image, restrained and tasteful, mobile-app ready.',
    'Avoid: fan community features, celebrity/idol elements, internet platform UI, messy text, watermark, logos, neon gradient placeholder, childish cartoon.'
  ].join('\n');
}

async function generateAlbumCover(album: Album) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is not configured');

  const model = process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1';
  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model,
      prompt: coverPromptForAlbum(album),
      size: '1024x1024'
    })
  });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(`OpenAI image generation failed: ${message.slice(0, 240)}`);
  }

  const data = (await response.json()) as { data?: Array<{ b64_json?: string; url?: string }> };
  let imageBytes: Buffer | null = null;
  const first = data.data?.[0];

  if (first?.b64_json) {
    imageBytes = Buffer.from(first.b64_json, 'base64');
  } else if (first?.url) {
    const imageResponse = await fetch(first.url);
    if (!imageResponse.ok) throw new Error('Generated image URL could not be downloaded');
    imageBytes = Buffer.from(await imageResponse.arrayBuffer());
  }

  if (!imageBytes) throw new Error('OpenAI did not return image data');

  fs.mkdirSync(coversDir, { recursive: true });
  const fileName = `${safeFileName(album.id)}.png`;
  fs.writeFileSync(path.join(coversDir, fileName), imageBytes);
  return `/covers/${fileName}`;
}

async function generateMissingCovers(albums: Album[], limit = maxAutoGeneratedCoversPerScan) {
  if (!shouldAutoGenerateCovers()) return { albums, generated: 0, failed: 0 };

  let generated = 0;
  let failed = 0;
  const nextAlbums: Album[] = [];

  for (const album of albums) {
    if (generated >= limit || !isPlaceholderCover(album.cover)) {
      nextAlbums.push(album);
      continue;
    }

    try {
      const cover = await generateAlbumCover(album);
      nextAlbums.push({ ...album, cover });
      generated += 1;
    } catch (error) {
      console.warn(`Cover generation failed for ${album.title}:`, error);
      nextAlbums.push(album);
      failed += 1;
    }
  }

  return { albums: nextAlbums, generated, failed };
}

function naturalSort(values: string[]) {
  return [...values].sort((a, b) => a.localeCompare(b, 'zh-Hans-CN', { numeric: true, sensitivity: 'base' }));
}

function normalizeDisplayName(value: string) {
  return value
    .replace(new RegExp(`\\.(${audioSuffixes.join('|')})$`, 'i'), '')
    .replace(new RegExp(`(${audioSuffixes.join('|')})$`, 'i'), '')
    .replace(/[._-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function stripNoise(value: string) {
  return normalizeDisplayName(value)
    .replace(/^[a-z]\s+/i, '')
    .replace(/^《(.+)》$/, '$1')
    .replace(/【[^】]*】/g, '')
    .replace(/\[[^\]]*]/g, '')
    .replace(/（[^）]*）/g, '')
    .replace(/\([^)]*\)/g, '')
    .replace(/\b(广播剧|有声剧|有声书|网课|课程|完结|更新|小说|原著)\b/gi, '')
    .replace(/\b(mp3|m4a|m4b|flac|aac|wav|opus|ogg)\b/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function cleanAlbumTitle(value: string) {
  return stripNoise(value)
    .replace(/^《(.+)》$/, '$1')
    .replace(/\s*[&＆].*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function chineseNumberToDigit(value: string) {
  const normalized = value.replace(/两/g, '二');
  const digits: Record<string, number> = {
    零: 0,
    〇: 0,
    一: 1,
    二: 2,
    三: 3,
    四: 4,
    五: 5,
    六: 6,
    七: 7,
    八: 8,
    九: 9,
    十: 10
  };
  if (/^\d+$/.test(normalized)) return Number(normalized);
  if (normalized === '十') return 10;
  if (normalized.startsWith('十')) return 10 + (digits[normalized.slice(1)] || 0);
  if (normalized.includes('十')) {
    const [ten, one] = normalized.split('十');
    return (digits[ten] || 1) * 10 + (digits[one] || 0);
  }
  return digits[normalized] || NaN;
}

function digitToChinese(value: string) {
  const digits = ['零', '一', '二', '三', '四', '五', '六', '七', '八', '九', '十'];
  const number = Number(value);
  if (!Number.isFinite(number)) return value;
  if (number <= 10) return digits[number];
  if (number < 20) return `十${digits[number - 10]}`;
  if (number < 100) {
    const tens = Math.floor(number / 10);
    const ones = number % 10;
    return `${digits[tens]}十${ones ? digits[ones] : ''}`;
  }
  return value;
}

function episodeInfoFromName(fileName: string) {
  const normalized = normalizeDisplayName(fileName).replace(/\s+/g, ' ');
  const patterns = [
    /第\s*([0-9一二三四五六七八九十两]+)\s*(集|期|话|章)\s*([上下])?/i,
    /(?:^|\s)([0-9]{1,3})\s*([上下])?(?=$|\s|[（(【\[.。·:：-])/i
  ];

  for (const pattern of patterns) {
    const match = normalized.match(pattern);
    if (!match) continue;

    const number = chineseNumberToDigit(match[1]);
    if (!Number.isFinite(number) || number <= 0 || number > 300) continue;

    const side = match[3] || match[2] || '';
    const label = `${String(number).padStart(2, '0')}${side ? ` ${side}` : ''}`;
    const rest = normalized
      .slice((match.index || 0) + match[0].length)
      .replace(/^[\s·.。:：-]+/, '')
      .replace(/\s+/g, ' ')
      .trim();
    return { number, label, rest };
  }

  return null;
}

function seasonLabelFromFolder(value: string) {
  const normalized = normalizeDisplayName(value);
  const match = normalized.match(/第?\s*([0-9一二三四五六七八九十两]+)\s*季/i);
  if (!match) return '';

  const rawNumber = match[1].replace('两', '二');
  const numberLabel = /^\d+$/.test(rawNumber) ? digitToChinese(rawNumber) : rawNumber;
  const side = /（\s*上\s*）|\(\s*上\s*\)|\b上\b/.test(value)
    ? '（上）'
    : /（\s*下\s*）|\(\s*下\s*\)|\b下\b/.test(value)
      ? '（下）'
      : '';
  return `第${numberLabel}季${side}`;
}

function shouldSplitAsSeasonFolder(value: string) {
  return Boolean(seasonLabelFromFolder(value));
}

function albumInfoForFile(root: string, file: string) {
  const relativeFile = path.relative(root, file);
  const parts = relativeFile.split(path.sep).filter(Boolean);
  const directoryParts = parts.slice(0, -1);

  if (!directoryParts.length) {
    return {
      key: path.basename(root),
      folderPath: root,
      title: normalizeDisplayName(path.basename(root))
    };
  }

  const first = directoryParts[0].toLowerCase();
  if (libraryFolderNames.has(directoryParts[0]) || libraryFolderNames.has(first)) {
    const albumPart = directoryParts[1] || directoryParts[0];
    const seasonPart = directoryParts[2];
    const hasSeasonFolder = Boolean(seasonPart && shouldSplitAsSeasonFolder(seasonPart));
    const keyParts = hasSeasonFolder
      ? directoryParts.slice(0, 3)
      : directoryParts[1]
        ? directoryParts.slice(0, 2)
        : directoryParts.slice(0, 1);
    const baseTitle = cleanAlbumTitle(albumPart);
    const seasonLabel = hasSeasonFolder ? seasonLabelFromFolder(seasonPart) : '';
    return {
      key: keyParts.join(path.sep),
      folderPath: path.join(root, ...keyParts),
      title: seasonLabel ? `${baseTitle} ${seasonLabel}` : baseTitle
    };
  }

  return {
    key: directoryParts[0],
    folderPath: path.join(root, directoryParts[0]),
    title: cleanAlbumTitle(directoryParts[0])
  };
}

function cleanEpisodeTitle(file: string, albumTitle: string, index: number) {
  const fallback = `${String(index + 1).padStart(2, '0')}`;
  const episodeInfo = episodeInfoFromName(path.basename(file));
  const albumTokens = new Set(
    stripNoise(albumTitle)
      .split(/\s+/)
      .filter((token) => token.length > 1)
  );
  const raw = stripNoise(path.basename(file))
    .replace(/第\s*[0-9一二三四五六七八九十两]+\s*季/gi, '')
    .replace(/^\d{1,3}\s*$/, (value) => value.padStart(2, '0'));
  const withoutAlbum = raw
    .split(/\s+/)
    .filter((token) => !albumTokens.has(token))
    .join(' ')
    .replace(/^(广播剧|有声书|网课|课程)\s*/i, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (episodeInfo) {
    if (!episodeInfo.rest) return episodeInfo.label;
    const rest = stripNoise(episodeInfo.rest)
      .split(/\s+/)
      .filter((token) => !albumTokens.has(token))
      .join(' ')
      .replace(/^[-·.。:：]+/, '')
      .trim();
    return rest && rest.length <= 28 ? `${episodeInfo.label} ${rest}` : episodeInfo.label;
  }

  if (!withoutAlbum) return fallback;
  if (withoutAlbum.length > 42 && /(\d{1,4}|[一二三四五六七八九十百零〇两]+)\s*(集|期|话|章)?/.test(withoutAlbum)) {
    return fallback;
  }

  return withoutAlbum;
}

function audioFileSortKey(file: string) {
  const info = episodeInfoFromName(path.basename(file));
  return {
    bucket: info ? 0 : 1,
    number: info?.number || Number.MAX_SAFE_INTEGER,
    name: path.basename(file)
  };
}

function sortAudioFiles(files: string[]) {
  return [...files].sort((a, b) => {
    const aKey = audioFileSortKey(a);
    const bKey = audioFileSortKey(b);
    if (aKey.bucket !== bKey.bucket) return aKey.bucket - bKey.bucket;
    if (aKey.number !== bKey.number) return aKey.number - bKey.number;
    return aKey.name.localeCompare(bKey.name, 'zh-Hans-CN', { numeric: true, sensitivity: 'base' });
  });
}

function isAudioFileName(fileName: string) {
  const lower = fileName.toLowerCase();
  if (audioExtensions.has(path.extname(lower))) return true;
  return audioSuffixes.some((suffix) => lower.endsWith(suffix));
}

function listAudioFiles(root: string, limit = maxScanFiles) {
  const files: string[] = [];

  function walk(dir: string) {
    if (files.length >= limit) return;
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (files.length >= limit) return;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!entry.name.startsWith('.')) walk(fullPath);
      } else if (isAudioFileName(entry.name)) {
        files.push(fullPath);
      }
    }
  }

  walk(root);
  return files;
}

function albumsFromFiles(root: string, files: string[]): Album[] {
  const groups = new Map<string, { folderPath: string; title: string; files: string[] }>();
  for (const file of files) {
    const albumInfo = albumInfoForFile(root, file);
    const group = groups.get(albumInfo.key) || { folderPath: albumInfo.folderPath, title: albumInfo.title, files: [] };
    group.files.push(file);
    groups.set(albumInfo.key, group);
  }

  return [...groups.entries()].map(([group, albumGroup], index) => {
    const sortedFiles = sortAudioFiles(albumGroup.files);
    const kind = inferKindFromPath(group);
    const title = albumGroup.title || `本地专辑 ${index + 1}`;
    const folderCover = findFolderCover(albumGroup.folderPath);
    return {
      id: `local-${stableId(group)}`,
      kind,
      title,
      subtitle: `${kind === 'drama' ? '广播剧' : kind === 'book' ? '有声书' : '网课'} · ${sortedFiles.length} 集`,
      cover: folderCover || fallbackCover(kind),
      creator: 'NAS 本地文件',
      status: 'new',
      progress: 0,
      totalEpisodes: sortedFiles.length,
      updatedAt: '刚刚扫描',
      tags: ['NAS', kind === 'drama' ? '广播剧' : kind === 'book' ? '有声书' : '网课'],
      description: `来自 NAS 目录：${group}`,
      author: '',
      cast: [],
      summary: '',
      genres: [],
      relationship: '',
      audience: '',
      finishStatus: '',
      aiMetaStatus: 'none',
      aiMetaUpdatedAt: '',
      episodes: sortedFiles.map((file, fileIndex) => ({
        id: `ep-${stableId(path.relative(root, file), 24)}`,
        title: cleanEpisodeTitle(file, title, fileIndex),
        duration: '--:--',
        progress: 0,
        filePath: file
      }))
    };
  });
}

app.get('/api/health', (_req, res) => {
  res.json({ ok: true, name: 'private-audio-room' });
});

app.get('/api/config', (_req, res) => {
  res.json({ config: getConfig() });
});

app.get('/api/albums', (req, res) => {
  const kind = req.query.kind as MediaKind | undefined;
  const query = String(req.query.q || '').trim().toLowerCase();
  const state = readState();
  let albums = state.albums;

  if (kind) albums = albums.filter((album) => album.kind === kind);
  if (query) {
    albums = albums.filter((album) => {
      return [
        album.title,
        album.subtitle,
        album.creator,
        album.description,
        album.author || '',
        album.summary || '',
        album.relationship || '',
        album.audience || '',
        album.finishStatus || '',
        ...(album.cast || []),
        ...(album.genres || []),
        ...album.tags
      ].some((value) =>
        value.toLowerCase().includes(query)
      );
    });
  }

  const category = String(req.query.category || '').trim();
  if (category) albums = albums.filter((album) => [...album.tags, ...(album.genres || [])].includes(category));

  res.json({ albums });
});

app.get('/api/albums/:id', (req, res) => {
  const album = readState().albums.find((item) => item.id === req.params.id);
  if (!album) return res.status(404).json({ error: 'Album not found' });
  res.json({ album });
});

app.get('/api/albums/:id/recommendations', (req, res) => {
  const limit = Math.max(1, Math.min(12, Number(req.query.limit || 6)));
  const state = readState();
  const album = state.albums.find((item) => item.id === req.params.id);
  if (!album) return res.status(404).json({ error: 'Album not found' });
  res.json({ recommendations: getAlbumRecommendations(album, state.albums, limit) });
});

app.patch('/api/albums/:id/cover', (req, res) => {
  const cover = String(req.body.cover || '').trim();
  if (!cover) return res.status(400).json({ error: 'Cover is required' });
  if (
    !cover.startsWith('data:image/') &&
    !cover.startsWith('linear-gradient(') &&
    !cover.startsWith('/covers/') &&
    !cover.startsWith('/assets/')
  ) {
    return res.status(400).json({ error: 'Cover must be an image data URL or supported gradient' });
  }

  const state = readState();
  const albumIndex = state.albums.findIndex((item) => item.id === req.params.id);
  if (albumIndex < 0) return res.status(404).json({ error: 'Album not found' });

  state.albums[albumIndex] = { ...state.albums[albumIndex], cover };
  writeState(state);
  res.json({ album: state.albums[albumIndex] });
});

app.patch('/api/albums/:id/metadata', (req, res) => {
  const state = readState();
  const albumIndex = state.albums.findIndex((item) => item.id === req.params.id);
  if (albumIndex < 0) return res.status(404).json({ error: 'Album not found' });

  const patch = metadataPatchFromBody(req.body || {});
  const nextTags = uniqueStrings([...patch.tags, ...patch.genres]);
  state.albums[albumIndex] = {
    ...state.albums[albumIndex],
    ...patch,
    tags: nextTags.length ? nextTags : state.albums[albumIndex].tags,
    aiMetaStatus: state.albums[albumIndex].aiMetaStatus === 'suggested' ? 'saved' : state.albums[albumIndex].aiMetaStatus,
    updatedAt: '刚刚整理'
  };
  writeState(state);
  res.json({ album: state.albums[albumIndex] });
});

app.post('/api/albums/:id/metadata/analyze', async (req, res) => {
  const state = readState();
  const albumIndex = state.albums.findIndex((item) => item.id === req.params.id);
  if (albumIndex < 0) return res.status(404).json({ error: 'Album not found' });

  try {
    const metadata = await analyzeAlbumMetadataWithDeepSeek(state.albums[albumIndex]);
    state.albums[albumIndex] = applyAiMetadataToAlbum(state.albums[albumIndex], metadata);
    writeState(state);
    res.json({ metadata, album: state.albums[albumIndex] });
  } catch (error) {
    state.albums[albumIndex] = {
      ...state.albums[albumIndex],
      aiMetaStatus: 'failed',
      aiMetaUpdatedAt: new Date().toISOString()
    };
    writeState(state);
    res.status(502).json({ error: error instanceof Error ? error.message : 'DeepSeek metadata analysis failed' });
  }
});

app.post('/api/metadata/analyze-batch', async (req, res) => {
  if (!process.env.DEEPSEEK_API_KEY) {
    return res.status(400).json({ error: 'DEEPSEEK_API_KEY is not configured' });
  }

  const kind = (req.body?.kind || 'drama') as MediaKind;
  const mode = String(req.body?.mode || 'all');
  const limit = Math.max(1, Math.min(200, Number(req.body?.limit || process.env.AI_METADATA_BATCH_LIMIT || 50)));
  const state = readState();
  const candidates = state.albums
    .map((album, index) => ({ album, index }))
    .filter(({ album }) => album.kind === kind)
    .filter(({ album }) => {
      if (mode === 'failed-only') return album.aiMetaStatus === 'failed';
      if (mode === 'missing-only') return !album.summary || !album.genres?.length || !album.cast?.length;
      return true;
    })
    .slice(0, limit);

  const results: Array<{ id: string; title: string; ok: boolean; error?: string }> = [];
  for (const { album, index } of candidates) {
    try {
      const metadata = await analyzeAlbumMetadataWithDeepSeek(album);
      state.albums[index] = applyAiMetadataToAlbum(state.albums[index], metadata);
      results.push({ id: album.id, title: album.title, ok: true });
    } catch (error) {
      state.albums[index] = {
        ...state.albums[index],
        aiMetaStatus: 'failed',
        aiMetaUpdatedAt: new Date().toISOString()
      };
      results.push({ id: album.id, title: album.title, ok: false, error: error instanceof Error ? error.message : 'DeepSeek metadata analysis failed' });
    }
  }

  writeState(state);
  res.json({
    albums: state.albums,
    total: candidates.length,
    updated: results.filter((result) => result.ok).length,
    failed: results.filter((result) => !result.ok).length,
    results
  });
});

app.post('/api/albums/:id/cover/generate', async (req, res) => {
  if (!process.env.OPENAI_API_KEY) {
    return res.status(400).json({ error: 'OPENAI_API_KEY is not configured' });
  }

  const state = readState();
  const albumIndex = state.albums.findIndex((item) => item.id === req.params.id);
  if (albumIndex < 0) return res.status(404).json({ error: 'Album not found' });

  try {
    const cover = await generateAlbumCover(state.albums[albumIndex]);
    state.albums[albumIndex] = { ...state.albums[albumIndex], cover };
    writeState(state);
    res.json({ album: state.albums[albumIndex] });
  } catch (error) {
    res.status(502).json({ error: error instanceof Error ? error.message : 'Cover generation failed' });
  }
});

app.get('/api/categories', (_req, res) => {
  res.json({ categories: readState().categories });
});

app.post('/api/categories', (req, res) => {
  const name = String(req.body.name || '').trim();
  if (!name) return res.status(400).json({ error: 'Category name is required' });

  const state = readState();
  const existing = state.categories.find((category) => category.name === name);
  if (existing) return res.json({ category: existing, categories: state.categories });

  const category: Category = {
    id: Buffer.from(name).toString('base64url').slice(0, 16),
    name
  };
  state.categories = [...state.categories, category];
  writeState(state);
  res.json({ category, categories: state.categories });
});

app.get('/api/favorite-folders', (_req, res) => {
  res.json({ favoriteFolders: readState().favoriteFolders });
});

app.post('/api/favorite-folders', (req, res) => {
  const name = stringField(req.body.name, 40);
  if (!name) return res.status(400).json({ error: 'Favorite folder name is required' });

  const state = readState();
  const existing = state.favoriteFolders.find((folder) => folder.name === name);
  if (existing) return res.json({ favoriteFolder: existing, favoriteFolders: state.favoriteFolders });

  const now = nowIso();
  const favoriteFolder: FavoriteFolder = {
    id: `fav-${stableId(`${name}-${now}`, 14)}`,
    name,
    albumIds: [],
    createdAt: now,
    updatedAt: now
  };
  state.favoriteFolders = [...state.favoriteFolders, favoriteFolder];
  writeState(state);
  res.json({ favoriteFolder, favoriteFolders: state.favoriteFolders });
});

app.post('/api/favorite-folders/:folderId/albums/:albumId', (req, res) => {
  const state = readState();
  const folderIndex = state.favoriteFolders.findIndex((folder) => folder.id === req.params.folderId);
  if (folderIndex < 0) return res.status(404).json({ error: 'Favorite folder not found' });
  if (!state.albums.some((album) => album.id === req.params.albumId)) return res.status(404).json({ error: 'Album not found' });

  state.favoriteFolders[folderIndex] = {
    ...state.favoriteFolders[folderIndex],
    albumIds: uniqueStrings([...state.favoriteFolders[folderIndex].albumIds, req.params.albumId]),
    updatedAt: nowIso()
  };
  writeState(state);
  res.json({ favoriteFolder: state.favoriteFolders[folderIndex], favoriteFolders: state.favoriteFolders });
});

app.delete('/api/favorite-folders/:folderId/albums/:albumId', (req, res) => {
  const state = readState();
  const folderIndex = state.favoriteFolders.findIndex((folder) => folder.id === req.params.folderId);
  if (folderIndex < 0) return res.status(404).json({ error: 'Favorite folder not found' });

  state.favoriteFolders[folderIndex] = {
    ...state.favoriteFolders[folderIndex],
    albumIds: state.favoriteFolders[folderIndex].albumIds.filter((albumId) => albumId !== req.params.albumId),
    updatedAt: nowIso()
  };
  writeState(state);
  res.json({ favoriteFolder: state.favoriteFolders[folderIndex], favoriteFolders: state.favoriteFolders });
});

app.get('/api/profile', (_req, res) => {
  res.json({ profile: readState().profile });
});

app.patch('/api/profile', (req, res) => {
  const avatar = String(req.body.avatar || '').trim();
  if (avatar && !avatar.startsWith('data:image/')) {
    return res.status(400).json({ error: 'Avatar must be an image data URL' });
  }

  const state = readState();
  state.profile = { ...state.profile, avatar };
  writeState(state);
  res.json({ profile: state.profile });
});

app.get('/api/nas', (_req, res) => {
  res.json({ nas: readState().nas });
});

app.post('/api/nas', (req, res) => {
  const current = readState();
  const root = String(req.body.root || '').trim();
  const nas: NasConfig = {
    type: req.body.type || 'local',
    label: req.body.label || '本地挂载 NAS',
    root,
    connected: root ? fs.existsSync(root) : false,
    lastScanAt: current.nas.lastScanAt
  };
  const next = { ...current, nas };
  writeState(next);
  res.json({ nas });
});

app.post('/api/scan', async (_req, res) => {
  const state = readState();
  const root = state.nas.root || process.env.AUDIO_ROOT || '';

  if (!root || !fs.existsSync(root)) {
    return res.status(400).json({ error: 'NAS root is not configured or not reachable' });
  }

  const files = listAudioFiles(root);
  const scannedAlbums = albumsFromFiles(root, files);
  const mergedAlbums = mergeManualMetadata(scannedAlbums, state.albums);
  const coverResult = await generateMissingCovers(mergedAlbums);
  const next = {
    nas: { ...state.nas, connected: true, lastScanAt: new Date().toISOString() },
    albums: coverResult.albums.length ? coverResult.albums : state.albums,
    categories: state.categories,
    favoriteFolders: state.favoriteFolders,
    profile: state.profile
  };
  writeState(next);
  res.json({
    albums: next.albums,
    count: files.length,
    nas: next.nas,
    covers: { generated: coverResult.generated, failed: coverResult.failed }
  });
});

app.get('/media/:albumId/:episodeId', (req, res) => {
  const state = readState();
  const album = state.albums.find((item) => item.id === req.params.albumId);
  const episode = album?.episodes.find((item) => item.id === req.params.episodeId);
  if (!episode?.filePath) return res.status(404).json({ error: 'Media file not found' });

  const resolved = path.resolve(episode.filePath);
  const root = path.resolve(state.nas.root || process.env.AUDIO_ROOT || path.dirname(resolved));
  if (!isPathInsideRoot(resolved, root) || !fs.existsSync(resolved)) {
    return res.status(403).json({ error: 'Media path is not allowed' });
  }

  const stat = fs.statSync(resolved);
  const fileSize = stat.size;
  const range = req.headers.range;
  const contentType = audioContentType(resolved);

  if (!range) {
    res.writeHead(200, {
      'Accept-Ranges': 'bytes',
      'Content-Length': fileSize,
      'Content-Type': contentType
    });
    fs.createReadStream(resolved).pipe(res);
    return;
  }

  const match = range.match(/bytes=(\d*)-(\d*)/);
  if (!match) return res.status(416).json({ error: 'Invalid range' });

  const start = match[1] ? Number(match[1]) : match[2] ? Math.max(fileSize - Number(match[2]), 0) : 0;
  const end = match[1] ? (match[2] ? Number(match[2]) : fileSize - 1) : fileSize - 1;
  if (start >= fileSize || end >= fileSize || start > end) {
    res.status(416).set('Content-Range', `bytes */${fileSize}`).end();
    return;
  }

  res.writeHead(206, {
    'Accept-Ranges': 'bytes',
    'Content-Range': `bytes ${start}-${end}/${fileSize}`,
    'Content-Length': end - start + 1,
    'Content-Type': contentType
  });
  fs.createReadStream(resolved, { start, end }).pipe(res);
});

const dirname = path.dirname(fileURLToPath(import.meta.url));
const distPath = path.resolve(dirname, '../dist');
app.use('/covers', express.static(coversDir));
if (fs.existsSync(distPath)) {
  app.use(express.static(distPath));
  app.get(/.*/, (_req, res) => res.sendFile(path.join(distPath, 'index.html')));
}

app.listen(port, () => {
  console.log(`Private Audio Room API listening on http://localhost:${port}`);
});
